# SOME DESCRIPTIVE TITLE.
# Copyright (C) 1990-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-08-11 04:42+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../c-api/exceptions.rst:8
msgid "Exception Handling"
msgstr ""

#: ../../../c-api/exceptions.rst:10
msgid ""
"The functions described in this chapter will let you handle and raise Python "
"exceptions.  It is important to understand some of the basics of Python "
"exception handling.  It works somewhat like the Unix :cdata:`errno` "
"variable: there is a global indicator (per thread) of the last error that "
"occurred.  Most functions don't clear this on success, but will set it to "
"indicate the cause of the error on failure.  Most functions also return an "
"error indicator, usually *NULL* if they are supposed to return a pointer, or "
"``-1`` if they return an integer (exception: the :cfunc:`PyArg_\\*` "
"functions return ``1`` for success and ``0`` for failure)."
msgstr ""

#: ../../../c-api/exceptions.rst:20
msgid ""
"When a function must fail because some function it called failed, it "
"generally doesn't set the error indicator; the function it called already "
"set it.  It is responsible for either handling the error and clearing the "
"exception or returning after cleaning up any resources it holds (such as "
"object references or memory allocations); it should *not* continue normally "
"if it is not prepared to handle the error.  If returning due to an error, it "
"is important to indicate to the caller that an error has been set.  If the "
"error is not handled or carefully propagated, additional calls into the "
"Python/C API may not behave as intended and may fail in mysterious ways."
msgstr ""

#: ../../../c-api/exceptions.rst:30
msgid ""
"The error indicator consists of three Python objects corresponding to the "
"result of ``sys.exc_info()``.  API functions exist to interact with the "
"error indicator in various ways.  There is a separate error indicator for "
"each thread."
msgstr ""

#: ../../../c-api/exceptions.rst:397
msgid "Standard Exceptions"
msgstr ""

#: ../../../c-api/exceptions.rst:399
msgid ""
"All standard Python exceptions are available as global variables whose names "
"are ``PyExc_`` followed by the Python exception name.  These have the type :"
"ctype:`PyObject\\*`; they are all class objects.  For completeness, here are "
"all the variables:"
msgstr ""

#: ../../../c-api/exceptions.rst:405
msgid "C Name"
msgstr ""

#: ../../../c-api/exceptions.rst:405
msgid "Python Name"
msgstr ""

#: ../../../c-api/exceptions.rst:405
msgid "Notes"
msgstr ""

#: ../../../c-api/exceptions.rst:407
msgid ":cdata:`PyExc_BaseException`"
msgstr ""

#: ../../../c-api/exceptions.rst:407
msgid ":exc:`BaseException`"
msgstr ""

#: ../../../c-api/exceptions.rst:407 ../../../c-api/exceptions.rst:409
#: ../../../c-api/exceptions.rst:411 ../../../c-api/exceptions.rst:413
#: ../../../c-api/exceptions.rst:421
msgid "\\(1)"
msgstr ""

#: ../../../c-api/exceptions.rst:409
msgid ":cdata:`PyExc_Exception`"
msgstr ""

#: ../../../c-api/exceptions.rst:409
msgid ":exc:`Exception`"
msgstr ""

#: ../../../c-api/exceptions.rst:411
msgid ":cdata:`PyExc_ArithmeticError`"
msgstr ""

#: ../../../c-api/exceptions.rst:411
msgid ":exc:`ArithmeticError`"
msgstr ""

#: ../../../c-api/exceptions.rst:413
msgid ":cdata:`PyExc_LookupError`"
msgstr ""

#: ../../../c-api/exceptions.rst:413
msgid ":exc:`LookupError`"
msgstr ""

#: ../../../c-api/exceptions.rst:415
msgid ":cdata:`PyExc_AssertionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:415
msgid ":exc:`AssertionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:417
msgid ":cdata:`PyExc_AttributeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:417
msgid ":exc:`AttributeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:419
msgid ":cdata:`PyExc_EOFError`"
msgstr ""

#: ../../../c-api/exceptions.rst:419
msgid ":exc:`EOFError`"
msgstr ""

#: ../../../c-api/exceptions.rst:421
msgid ":cdata:`PyExc_EnvironmentError`"
msgstr ""

#: ../../../c-api/exceptions.rst:421
msgid ":exc:`EnvironmentError`"
msgstr ""

#: ../../../c-api/exceptions.rst:423
msgid ":cdata:`PyExc_FloatingPointError`"
msgstr ""

#: ../../../c-api/exceptions.rst:423
msgid ":exc:`FloatingPointError`"
msgstr ""

#: ../../../c-api/exceptions.rst:425
msgid ":cdata:`PyExc_IOError`"
msgstr ""

#: ../../../c-api/exceptions.rst:425
msgid ":exc:`IOError`"
msgstr ""

#: ../../../c-api/exceptions.rst:427
msgid ":cdata:`PyExc_ImportError`"
msgstr ""

#: ../../../c-api/exceptions.rst:427
msgid ":exc:`ImportError`"
msgstr ""

#: ../../../c-api/exceptions.rst:429
msgid ":cdata:`PyExc_IndexError`"
msgstr ""

#: ../../../c-api/exceptions.rst:429
msgid ":exc:`IndexError`"
msgstr ""

#: ../../../c-api/exceptions.rst:431
msgid ":cdata:`PyExc_KeyError`"
msgstr ""

#: ../../../c-api/exceptions.rst:431
msgid ":exc:`KeyError`"
msgstr ""

#: ../../../c-api/exceptions.rst:433
msgid ":cdata:`PyExc_KeyboardInterrupt`"
msgstr ""

#: ../../../c-api/exceptions.rst:433
msgid ":exc:`KeyboardInterrupt`"
msgstr ""

#: ../../../c-api/exceptions.rst:435
msgid ":cdata:`PyExc_MemoryError`"
msgstr ""

#: ../../../c-api/exceptions.rst:435
msgid ":exc:`MemoryError`"
msgstr ""

#: ../../../c-api/exceptions.rst:437
msgid ":cdata:`PyExc_NameError`"
msgstr ""

#: ../../../c-api/exceptions.rst:437
msgid ":exc:`NameError`"
msgstr ""

#: ../../../c-api/exceptions.rst:439
msgid ":cdata:`PyExc_NotImplementedError`"
msgstr ""

#: ../../../c-api/exceptions.rst:439
msgid ":exc:`NotImplementedError`"
msgstr ""

#: ../../../c-api/exceptions.rst:441
msgid ":cdata:`PyExc_OSError`"
msgstr ""

#: ../../../c-api/exceptions.rst:441
msgid ":exc:`OSError`"
msgstr ""

#: ../../../c-api/exceptions.rst:443
msgid ":cdata:`PyExc_OverflowError`"
msgstr ""

#: ../../../c-api/exceptions.rst:443
msgid ":exc:`OverflowError`"
msgstr ""

#: ../../../c-api/exceptions.rst:445
msgid ":cdata:`PyExc_ReferenceError`"
msgstr ""

#: ../../../c-api/exceptions.rst:445
msgid ":exc:`ReferenceError`"
msgstr ""

#: ../../../c-api/exceptions.rst:445
msgid "\\(2)"
msgstr ""

#: ../../../c-api/exceptions.rst:447
msgid ":cdata:`PyExc_RuntimeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:447
msgid ":exc:`RuntimeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:449
msgid ":cdata:`PyExc_SyntaxError`"
msgstr ""

#: ../../../c-api/exceptions.rst:449
msgid ":exc:`SyntaxError`"
msgstr ""

#: ../../../c-api/exceptions.rst:451
msgid ":cdata:`PyExc_SystemError`"
msgstr ""

#: ../../../c-api/exceptions.rst:451
msgid ":exc:`SystemError`"
msgstr ""

#: ../../../c-api/exceptions.rst:453
msgid ":cdata:`PyExc_SystemExit`"
msgstr ""

#: ../../../c-api/exceptions.rst:453
msgid ":exc:`SystemExit`"
msgstr ""

#: ../../../c-api/exceptions.rst:455
msgid ":cdata:`PyExc_TypeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:455
msgid ":exc:`TypeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:457
msgid ":cdata:`PyExc_ValueError`"
msgstr ""

#: ../../../c-api/exceptions.rst:457
msgid ":exc:`ValueError`"
msgstr ""

#: ../../../c-api/exceptions.rst:459
msgid ":cdata:`PyExc_WindowsError`"
msgstr ""

#: ../../../c-api/exceptions.rst:459
msgid ":exc:`WindowsError`"
msgstr ""

#: ../../../c-api/exceptions.rst:459
msgid "\\(3)"
msgstr ""

#: ../../../c-api/exceptions.rst:461
msgid ":cdata:`PyExc_ZeroDivisionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:461
msgid ":exc:`ZeroDivisionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:494
msgid "Notes:"
msgstr ""

#: ../../../c-api/exceptions.rst:497
msgid "This is a base class for other standard exceptions."
msgstr ""

#: ../../../c-api/exceptions.rst:500
msgid "This is the same as :exc:`weakref.ReferenceError`."
msgstr ""

#: ../../../c-api/exceptions.rst:503
msgid ""
"Only defined on Windows; protect code that uses this by testing that the "
"preprocessor macro ``MS_WINDOWS`` is defined."
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_BaseException"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_Exception"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_ArithmeticError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_LookupError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_AssertionError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_AttributeError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_EOFError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_EnvironmentError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_FloatingPointError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_IOError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_ImportError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_IndexError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_KeyError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_KeyboardInterrupt"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_MemoryError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_NameError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_NotImplementedError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_OSError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_OverflowError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_ReferenceError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_RuntimeError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_SyntaxError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_SystemError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_SystemExit"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_TypeError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_ValueError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_WindowsError"
msgstr ""

#: ../../../c-api/exceptions.rst:464
msgid "PyExc_ZeroDivisionError"
msgstr ""
